version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123@@
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
