name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/azure-sql-edge
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: Admin123@@
          MSSQL_PID: Developer
        ports:
          - 1433:1433

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt
          if-no-files-found: ignore
